### ISSUE TITLE
Package does not work with trpc 10

### ISSUE THREAD

**Issue by nicholasoxford** [ggrandi/trpc-remix#2]
I would love to help to get this updated

**Comment by JClackett** [comment]
Yes pleaseeeee

**Comment by nicholasoxford** [comment]
I got you bro

**Comment by ggrandi** [comment]
if you need any support, I'd love to help out. I just haven't really gotten around to updating the repo in a while. I'm also happy to merge any pull requests you'd make

**Comment by nicholasoxford** [comment]
I made great progress here the other day: https://github.com/nicholasoxford/trpc-remix, let me pull it down and work at it again today

**Comment by JClackett** [comment]
@nicholasoxford That would be great!

**Comment by rodbs** [comment]
Any plans to get it updated? @nicholasoxford ?

**Comment by JClackett** [comment]
All you actually need to do is use the fetch adapter from trpc, my team has a boilerplate that uses it, check https://github.com/NoQuarterTeam/boilerplate

Look at the trpc file in remix api route folder
